### ISSUE TITLE
Communicate problem when machine not in k8s cluster

### ISSUE THREAD

**Issue by miracle-jia** [fujitatomoya/ros_k8s#29]
This repository is so greatful!

I have the following use case: my roscore is deployed in a k8s cluster, but developers need to debug locally due to certain algorithms. They need to register their local development machine with the roscore, but the development machine is not a node in the k8s cluster. We can discover the published topics between the development machine and the container using "rostopic list", and we can also echo messages from the development machine to the container using "rostopic echo". However, there is a problem echo messages from the container to the development machine. We register with the roscore using IP. We are using the Calico network for our cluster. Is there a solution or something we are doing wrong?

So far, we have only been able to workaround this issue by using the "host-network" mode, which, unfortunately, consumes a lot of host ports.

Anyone can help us? Thank you.

**Comment by fujitatomoya** [comment]
@miracle-jia thanks for creating issue.

> They need to register their local development machine with the roscore, but the development machine is not a node in the k8s cluster.

i am not really sure what meant here.

- rosmaster is running as a pod in k8s cluster, right. and network is calico bound to the pods?
- how this development machine access the rosmaster? since rosmaster is running in the cluster with calico, IP address for rosmaster is the cluster IP address, which cannot be used by physical network?

can you describe the network configuration for the pods and host system?

basically, rosmaster provides XMLRPC server to share the configuration data such as api path and port numbers. that said, if it accesses to rosmaster, that means it can get the list topics and services, since those are just configuration data in the rosmaster.
but the data path is different path, that is constructed with `TCP/IP` (default) or `UDP/IP` for *each endpoint*, that said endpoints should be able to ping each other in the network.

i guess in your case,

- topic list can be got from both side. this is because rosmaster is accessible from both side.
- `puhlisher(host)` -> `subscription(pod)` cannot be done since pod cannot access the physical network that publisher is running? and `puhlisher(pod)` -> `subscription(host)` can be done since pod cannot access the physical network that publisher is running. or vice-versa?

anyway i would like to have more detailed network configuration for entire cluster and host system.

**Comment by fujitatomoya** [comment]
@miracle-jia since there is no further update or information, i will go ahead to close this.
